project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - r-and-rstudio.qmd
    - experimental-data.qmd
    - logical-operations.qmd

website:
  title: "BIOSCI 504"
  navbar:
    left:
      - href: r-and-rstudio.qmd
        text: "R and RStudio"
      - href: experimental-data.qmd
        text: "Experimental data"
      - href: logical-operations.qmd
        text: "Logical operations"

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
